### ISSUE TITLE
 interfacing the project to the cloud

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#15]
Ramneet - What issues did you face interfacing the project to the cloud? How did you resolve them? Modify the charts as instructed.

**Comment by embedded92** [comment]
-Issues faced while interfacing the project to the cloud:
Sometimes due to the low signal strength of wifi(usually between -70to -80dBm) in my room, ESP8266 was not able to connect to Wi-Fi and hence was not able to connect to MQTT broker(cloud).
To resolve this issue I had to move out of my room and then try the connection, also I requested my pg owner to install a signal repeater.

-Modify the charts as instructed:
We are using the trial version of thingspeak that has only limited options to add visuals and graphs to represent data. We have tried to make a few changes to make data representation more clear and readable. In order to do so, we have done two 2 things, first, added titles to the X and Y axis, and second, added a button-like visual to Field 4 which represents the "Emergency" situation.

-Bug:
While demonstrating the project in the class after my presentation, I was not able to show updated data on the cloud. The reason being, while making the hardware connections more clear I somehow connected the RX and TX of BBB-ESP8266 wrong(used 9-11 instead of 11-13 pins of BBB). Due to which BBB was not able to send any data to ESP and ESP was unable to update the cloud. 
I, later on, made the connections right and gave a demo in the class.
