### ISSUE TITLE
PCB and more

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#18]
Navjot and Ramneet - What's the difference between a breadboard PCB and a Zero PCB? Why do you think your project has Real time processing features without FreeRTOS?

**Comment by Saininavjot** [comment]
What the difference between a breadboard PCB and a Zero PCB?
Zero PCB: Zero PCB is basically a general-purpose printed circuit board (PCB), also known as perfboard or DOT PCB. It is a thin rigid copper sheet with holes pre-drilled at standard intervals across a grid with 2.54mm (0.1-inch) spacing between holes. Each hole is encircled by a round or square copper pad so that component lead can be inserted into the hole and soldered around the pad without short-circuiting the nearby pads and other leads. For connecting the lead of component with another lead, solder these together or join these using a suitable conducting wire.
Solderable Breadboard PCB: The soldereable breadboard would be a good alternative to custom PCB for the projects, since the layout of the holes are nearly identical to that of the solder less breadboard. In some cases, it is better to prototype the circuit straight to the solderable breadboard. After testing the circuit on the Breadboard, then the prototype can be copied exactly to the soderable Breadboard. However, on the Zero PCB, one needs to re-arrange the circuit and have to create a PCB design before soldering the components on the Zero PCB. Moreover, in zerp PCB, traces have to be made with solder wire. But in Breadboard PCB, there is no need to create PCB design. Only thing that is needs to be done in breadboard PCB is to copy the circuit from Breadboard to solderable Breadboard and solder it permanently. The hole pattern of solderable Breadboard matches solderless breadboards of the same size.

**Comment by embedded92** [comment]
There are two types of RTOS depending on the applications
1) hard real-time OS
2) Soft real-time OS

Freertos can be used as both, depending on the application and implementation. in our project, we have used Embedded Linux on Beaglebone black which is a soft real-time operating system.
One of the main features of RTOS is the ability to run multiple tasks in a timely manner. In our project, we have used multiple threads using "pthread" library for different components of the system. And scheduler of our embedded Linux kernel schedules them in a timely manner. In multi-threaded implementation different components seem to work in parallel and tasks will not wait for one another to be completed. It is the scheduler that uses different scheduling techniques to make the system work in Real-Time. 
So, we can conclude that our system is working in Real-Time but this project is a soft Real-Time application.
