### ISSUE TITLE
Button & Buzzer Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#4]
Navjot - 1) What issues did you face when interfacing the button and buzzer? 2) How did you resolve them? 3) On the terminal you were getting "Operation not permitted" error. How should you manage it?

**Comment by embedded92** [comment]
Issues that we faced while Interfacing Buzzer and Push Button with Beaglebone Black:
1. Accessing GPIO pins of Beaglebone Black: The major issue is that we can not program the GPIO pins of Beaglebone Black directly. Multiple layers are present between user and Beaglebone Black. First of all, major challenge is to research about ways by which we can access the GPIO pins of Beaglebone Black.
Resolving this issue: We have done a thorough research and come across various ways of accessing and programming GPIO pins of Beaglebone black. Some of the methods are:
a) Using Command line terminal commands:
Before writing and reading data from the GPIO pins, we need to export the pins and give direction to the pin (input or output). We interact with BBB pins via a set of files that are read/written to. To reach the directory where these files are located, enter the following.
cd /sys/class/gpio
To access any GPIO pin, first need to export that file using command:
echo  22 > export, Where 22 represent gpio pin 22.
Echo 1 > value, to set value of pin 1 or 0
Echo out > direction, to send the direction of the pin
b)  Accessing pins through C library:
This method we have included in our project to access GPIO pins through C files:
Gpio.c and  Gpio.h, These files are included in our C project to access the pins.
The links for these files are:
https://gist.github.com/ajmontag/4013192
https://developer.ridgerun.com/wiki/index.php?title=Gpio-int-test.c 
2. File path declaration in Program:
Earlier, in the program, we have not given full path of file to access pins. Because of this, program was showing error. Moreover, we get to know later on that we have to close file that means free up the pins before using these pins. 
Resolving this Issue: The full path of file export path is given at which gpio pins are present on the gpio_control.c files. Everytime, if we want to read or write values to the pin, we have to give paths for files.
  fd = open("/sys/class/gpio/export", O_WRONLY);//file descriptor
We created a separated function called clean_up_system( ) in which we free up the pins to be used in main( ) function. So, before performing read and write operation in the main code, we called clean_up_system( ) function in main program.
/*
 * Freeup all the pins used in the project
 */
static void clean_up_system(void)
{
    // unexport and free up gpios
    gpio_control_free_pin(BUZZER_GPIO_PIN);
    gpio_control_free_pin(SWITCH_GPIO_PIN);
}
2. Terminal "Operation not permitted" error. How should you manage it?
While trying to access the GPIO pins through line, I faced issue while exporting pins. There is error “Operation not permitted” when I was running command : echo 22 > export.
To resolve this issue:
I research about this error on Google and come across various options to resolve this issue:
1. While accessing pins, I access the pins by becoming root user using command: sudo su
As a root, it is possible to access the pins.
Secondly, I unexport the pin first before exporting it. As, sometimes resources are busy, so to use any pin. First, we need to set the pin free by unexporting it. 
echo 20 > unexport
root@beaglebone:/sys/class/gpio# ls
export  gpio111  gpio115  gpio13  gpio2   gpio26  gpio31  gpio35  gpio39  gpio46  gpio5   gpio61  gpio66  gpio7   gpio73  gpio77  gpio80  gpio88     gpiochip32
gpio10  gpio112  gpio116  gpio14  gpio20  gpio27  gpio32  gpio36  gpio4   gpio47  gpio50  gpio62  gpio67  gpio70  gpio74  gpio78  gpio81  gpio89     gpiochip64
gpio11  gpio113  gpio117  gpio15  gpio22  gpio3   gpio33  gpio37  gpio44  gpio48  gpio51  gpio63  gpio68  gpio71  gpio75  gpio79  gpio86  gpio9      gpiochip96
gpio110  gpio114  gpio12   gpio19  gpio23  gpio30  gpio34  gpio38  gpio45  gpio49  gpio60  gpio65  gpio69  gpio72  gpio76  gpio8   gpio87  gpiochip0  unexport
root@beaglebone:/sys/class/gpio# echo 20 > export
bash: echo: write error: Operation not permitted
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > export
root@beaglebone:/sys/class/gpio# cd gpio20
root@beaglebone:/sys/class/gpio/gpio20# echo out > direction
root@beaglebone:/sys/class/gpio/gpio20# cat direction
out
root@beaglebone:/sys/class/gpio/gpio20# echo 1 > value
root@beaglebone:/sys/class/gpio/gpio20# cat value
1
root@beaglebone:/sys/class/gpio/gpio20#

**Comment by embedded92** [comment]
Issues that we faced while Interfacing Buzzer and Push Button with Beaglebone Black:
1. Accessing GPIO pins of Beaglebone Black: The major issue is that we can not program the GPIO pins of Beaglebone Black directly. Multiple layers are present between user and Beaglebone Black. First of all, major challenge is to research about ways by which we can access the GPIO pins of Beaglebone Black.
Resolving this issue: We have done a thorough research and come across various ways of accessing and programming GPIO pins of Beaglebone black. Some of the methods are:
a) Using Command line terminal commands:
Before writing and reading data from the GPIO pins, we need to export the pins and give direction to the pin (input or output). We interact with BBB pins via a set of files that are read/written to. To reach the directory where these files are located, enter the following.
cd /sys/class/gpio
To access any GPIO pin, first need to export that file using command:
echo  22 > export, Where 22 represent gpio pin 22.
Echo 1 > value, to set value of pin 1 or 0
Echo out > direction, to send the direction of the pin
b)  Accessing pins through C library:
This method we have included in our project to access GPIO pins through C files:
Gpio.c and  Gpio.h, These files are included in our C project to access the pins.
The links for these files are:
https://gist.github.com/ajmontag/4013192
https://developer.ridgerun.com/wiki/index.php?title=Gpio-int-test.c 
2. File path declaration in Program:
Earlier, in the program, we have not given full path of file to access pins. Because of this, program was showing error. Moreover, we get to know later on that we have to close file that means free up the pins before using these pins. 
Resolving this Issue: The full path of file export path is given at which gpio pins are present on the gpio_control.c files. Everytime, if we want to read or write values to the pin, we have to give paths for files.
  fd = open("/sys/class/gpio/export", O_WRONLY);//file descriptor
We created a separated function called clean_up_system( ) in which we free up the pins to be used in main( ) function. So, before performing read and write operation in the main code, we called clean_up_system( ) function in main program.
/*
 * Freeup all the pins used in the project
 */
static void clean_up_system(void)
{
    // unexport and free up gpios
    gpio_control_free_pin(BUZZER_GPIO_PIN);
    gpio_control_free_pin(SWITCH_GPIO_PIN);
}
2. Terminal "Operation not permitted" error. How should you manage it?
While trying to access the GPIO pins through line, I faced issue while exporting pins. There is error “Operation not permitted” when I was running command : echo 22 > export.
To resolve this issue:
I research about this error on Google and come across various options to resolve this issue:
1. While accessing pins, I access the pins by becoming root user using command: sudo su
As a root, it is possible to access the pins.
Secondly, I unexport the pin first before exporting it. As, sometimes resources are busy, so to use any pin. First, we need to set the pin free by unexporting it. 
echo 20 > unexport
root@beaglebone:/sys/class/gpio# ls
export  gpio111  gpio115  gpio13  gpio2   gpio26  gpio31  gpio35  gpio39  gpio46  gpio5   gpio61  gpio66  gpio7   gpio73  gpio77  gpio80  gpio88     gpiochip32
gpio10  gpio112  gpio116  gpio14  gpio20  gpio27  gpio32  gpio36  gpio4   gpio47  gpio50  gpio62  gpio67  gpio70  gpio74  gpio78  gpio81  gpio89     gpiochip64
gpio11  gpio113  gpio117  gpio15  gpio22  gpio3   gpio33  gpio37  gpio44  gpio48  gpio51  gpio63  gpio68  gpio71  gpio75  gpio79  gpio86  gpio9      gpiochip96
gpio110  gpio114  gpio12   gpio19  gpio23  gpio30  gpio34  gpio38  gpio45  gpio49  gpio60  gpio65  gpio69  gpio72  gpio76  gpio8   gpio87  gpiochip0  unexport
root@beaglebone:/sys/class/gpio# echo 20 > export
bash: echo: write error: Operation not permitted
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > export
root@beaglebone:/sys/class/gpio# cd gpio20
root@beaglebone:/sys/class/gpio/gpio20# echo out > direction
root@beaglebone:/sys/class/gpio/gpio20# cat direction
out
root@beaglebone:/sys/class/gpio/gpio20# echo 1 > value
root@beaglebone:/sys/class/gpio/gpio20# cat value
1
root@beaglebone:/sys/class/gpio/gpio20#

**Comment by Saininavjot** [comment]
Issues that we faced while Interfacing Buzzer and Push Button with Beaglebone Black:
1. Accessing GPIO pins of Beaglebone Black: The major issue is that we can not program the GPIO pins of Beaglebone Black directly. Multiple layers are present between user and Beaglebone Black. First of all, major challenge is to research about ways by which we can access the GPIO pins of Beaglebone Black.
Resolving this issue: We have done a thorough research and come across various ways of accessing and programming GPIO pins of Beaglebone black. Some of the methods are:
a) Using Command line terminal commands:
Before writing and reading data from the GPIO pins, we need to export the pins and give direction to the pin (input or output). We interact with BBB pins via a set of files that are read/written to. To reach the directory where these files are located, enter the following.
cd /sys/class/gpio
To access any GPIO pin, first need to export that file using command:
echo  22 > export, Where 22 represent gpio pin 22.
Echo 1 > value, to set value of pin 1 or 0
Echo out > direction, to send the direction of the pin
b)  Accessing pins through C library:
This method we have included in our project to access GPIO pins through C files:
Gpio.c and  Gpio.h, These files are included in our C project to access the pins.
The links for these files are:
https://gist.github.com/ajmontag/4013192
https://developer.ridgerun.com/wiki/index.php?title=Gpio-int-test.c 
2. File path declaration in Program:
Earlier, in the program, we have not given full path of file to access pins. Because of this, program was showing error. Moreover, we get to know later on that we have to close file that means free up the pins before using these pins. 
Resolving this Issue: The full path of file export path is given at which gpio pins are present on the gpio_control.c files. Everytime, if we want to read or write values to the pin, we have to give paths for files.
  fd = open("/sys/class/gpio/export", O_WRONLY);//file descriptor
We created a separated function called clean_up_system( ) in which we free up the pins to be used in main( ) function. So, before performing read and write operation in the main code, we called clean_up_system( ) function in main program.
/*
 * Freeup all the pins used in the project
 */
static void clean_up_system(void)
{
    // unexport and free up gpios
    gpio_control_free_pin(BUZZER_GPIO_PIN);
    gpio_control_free_pin(SWITCH_GPIO_PIN);
}
2. Terminal "Operation not permitted" error. How should you manage it?
While trying to access the GPIO pins through line, I faced issue while exporting pins. There is error “Operation not permitted” when I was running command : echo 22 > export.
To resolve this issue:
I research about this error on Google and come across various options to resolve this issue:
1. While accessing pins, I access the pins by becoming root user using command: sudo su
As a root, it is possible to access the pins.
Secondly, I unexport the pin first before exporting it. As, sometimes resources are busy, so to use any pin. First, we need to set the pin free by unexporting it. 
echo 20 > unexport
root@beaglebone:/sys/class/gpio# ls
export  gpio111  gpio115  gpio13  gpio2   gpio26  gpio31  gpio35  gpio39  gpio46  gpio5   gpio61  gpio66  gpio7   gpio73  gpio77  gpio80  gpio88     gpiochip32
gpio10  gpio112  gpio116  gpio14  gpio20  gpio27  gpio32  gpio36  gpio4   gpio47  gpio50  gpio62  gpio67  gpio70  gpio74  gpio78  gpio81  gpio89     gpiochip64
gpio11  gpio113  gpio117  gpio15  gpio22  gpio3   gpio33  gpio37  gpio44  gpio48  gpio51  gpio63  gpio68  gpio71  gpio75  gpio79  gpio86  gpio9      gpiochip96
gpio110  gpio114  gpio12   gpio19  gpio23  gpio30  gpio34  gpio38  gpio45  gpio49  gpio60  gpio65  gpio69  gpio72  gpio76  gpio8   gpio87  gpiochip0  unexport
root@beaglebone:/sys/class/gpio# echo 20 > export
bash: echo: write error: Operation not permitted
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > unexport
bash: echo: write error: Invalid argument
root@beaglebone:/sys/class/gpio# echo 20 > export
root@beaglebone:/sys/class/gpio# cd gpio20
root@beaglebone:/sys/class/gpio/gpio20# echo out > direction
root@beaglebone:/sys/class/gpio/gpio20# cat direction
out
root@beaglebone:/sys/class/gpio/gpio20# echo 1 > value
root@beaglebone:/sys/class/gpio/gpio20# cat value
1
root@beaglebone:/sys/class/gpio/gpio20#
